### ISSUE TITLE
Als gebruiker wil ik de samenvatting van het verzoek kunnen opslaan op mijn computer of telefoon

### ISSUE THREAD

**Issue by versteegerik** [mijnapp/mijnapp-frontend#29]
**Titel**
Als gebruiker wil ik de samenvatting van het verzoek kunnen opslaan op mijn computer of telefoon

**Achtergrond**
Gebruikers willen graag een 'bewijs' van de wijziging hebben. Denk aan een print knop of een pdf downloaden.

**Beschrijving**
De gebruiker kan een PDF downloaden van de samenvattingspagina. Deze kan hij dan lokaal op zijn telefoon of pc opslaan en eventueel printen.

**Comment by SjoerdKuperus** [comment]
Opgelost in Sprint 4.
